### PR TITLE
Enhance Identity Info Search & Local Login for Dev

### PR DESCRIPTION
**Pull request by jhyderjhyder**
Not sure how you wanted the pages to work but when searching for users without very simple pages 250 results was a bit much.

### CODE REVIEW

**Comment by piyush-khandelwal-sp** [comment]
@jhyderjhyder the local auto login is not working for me.. If its still working for you (small variable change) then let me know and I will merge this PR.

**Comment by jhyderjhyder** [comment]
On a windows box its working for me.  I need to get a Linux box setup, but did you try export on the mac/linux?     Also you could try this env variable to see if it adds your custom attributes to your dropdown.  NG_APP_IDENTITY_SEARCH.   


NG_APP_IDENTITY_SEARCH=costCenter,mname npm start
https://www.npmjs.com/package/@ngx-env/builder

**Comment by piyush-khandelwal-sp** [comment]
@jhyderjhyder do you need paging here? Because I fixed it by returning only identities in previous pull.. [yours](https://github.com/piyush-khandelwal-sp/idn-admin-console/pull/233/commits/e2eb245417890f312c47b8e39606f39d9e27ff64) is putting other types like entitlements etc in the result for identity search? 

in [my commit](https://github.com/piyush-khandelwal-sp/idn-admin-console/pull/233/commits/45da1d7bd427e57d2e2a7029f575f3c51b0e700b#diff-1eb670eb7aa2b10199183a70a768357cd46b2b12e4e6ef31d2aab881706e9506) see the results.

**Comment by jhyderjhyder** [comment]
I liked what you did on the search.  I added the option for starts with and Manager.  I think you can see the value of returning a subset of data.  Also your good at picking object names, so you might want to update the page object.  If you like the pages I should be able to do this on all the other objects such as the requests that for sure need pages.

**Comment by piyush-khandelwal-sp** [comment]
@jhyderjhyder this looks fantastic mate.. mind blowing :) I have done a few things.. 

- updated with new [v2.1.0 release](https://github.com/piyush-khandelwal-sp/idn-admin-console/pull/233/commits/69935853e2ced7761ec8e44c05a84e9312b14020) main branch
- fixed `searchAccountsPaged()` to return only [identities](https://github.com/piyush-khandelwal-sp/idn-admin-console/pull/233/commits/5eafcc152d6d202322d01cf3cecaefa18f0ccafc)
- [Fixed a few null errors](https://github.com/piyush-khandelwal-sp/idn-admin-console/pull/233/commits/5eafcc152d6d202322d01cf3cecaefa18f0ccafc) I was seeing for users who didn't have any AP / roles etc.. 

Found a bug
- Do a `user*` search and I got 5 users back `?count=true&limit=5&offset=0`. It shows next for page. But when clicking it says no record found since it's going to next offset page `?count=true&limit=5&offset=5`. I think `X-Total-Count` needs to be taken into consideration to calculate nextPage
- Also when the above page is there on no record found.. I do the same search `user*` it has not reset the page offset `?count=true&limit=5&offset=5`. I think at this stage it should have reset the offset or call to brand new call.

Please see if everything is working per your design.. Maybe we should do the following (just a thought)?
- Help with the above bug fix.
- Should we add Work Items for the searched user as a tab as well? 
- Should we enhance the CSV download with the data?

Once confirmed, I am happy to merge this into a v2.2.0 release.

**Comment by jhyderjhyder** [comment]
Thanks for the feedback and sorry, and about all the commits, I forgot about that I had already done a push request, I got carried away and forgot about it being public.  Do you want to create a release Candidate branch?  That way if page changes are not what users what, then you will not have much of a rollback?

On the "pagination" I think I need to redo some of the code so it fits with bootstrap's pagination look.  Unless you have a better idea for how the pages should look, the bootstap code is really more appealing to me than the simple next button.  
https://getbootstrap.com/docs/5.0/components/pagination/

Once that's done for the identity page, I will apply the same logic to access request page.  If it works for two models, then adding pagination to the other pages should be cut and paste.  

I want to add workitems for sure and also the new ownership of entitlements.

**Comment by piyush-khandelwal-sp** [comment]
@jhyderjhyder i have already added work item if you want to get the latest and test … I can potentially look at entitlement ownership as that is a new API… then I will merge into a release.. we should probably keep one PR per feature.. won’t do a RC.. it’s not a complex project :)

**Review by piyush-khandelwal-sp — APPROVED** [review]
👍

**Pull request merged**
